[package]
name = "lld-pg"
version = "0.1.0"
authors = ["tbistr"]

description = "lld-script parser and generator"

license = "MIT"

[lib]
path = "./src/lib.rs"

edition = "2021"

[dependencies]
nom = "7.1.0"
